### ISSUE TITLE
Set up work environment

### ISSUE THREAD

**Issue by cjhet02** [ChicoState/MusicMirror#1]

**Comment by khasek** [comment]
We have decided to start this project as a web application. Everybody's work environment should include React, Django, Python, and Javascript.

In order to complete this issue, the following things need to happen:

1. Find tutorials to help you learn (just enough to be dangerous/productive)
2. Find a .gitignore for it and add it to your repo
3. Set up a development environment and confirm the whole team has it configured consistently
4. Commit the initial setup of the tech to your repository

Question 1: Will it be an issue that our dev team is using several different operating systems? Will we need Docker or something similar?
