### ISSUE TITLE
As a Spotify user I want to be able to connect my account to the app

### ISSUE THREAD

**Issue by cjhet02** [ChicoState/MusicMirror#2]

**Comment by khasek** [comment]
Spotify is one of the most popular music streaming services out there; it is also one of the most developer-friendly and provides excellent documentation for the steps needed to access data. This makes Spotify a good candidate for our first supported service.

In order to resolve this issue, our program should:

1. Accept login credentials for an active Spotify account
2. Display playlists associated with that account.

Question 1: What information do we want to display about the songs on our playlists? Song title, artist, album, ISRC code, song length, genre tags...?

Note 1: I do not think we actually require a MusicMirror login for this step. It's certainly something we'll want early on, but it isn't necessarily required for our the MVP of our first sprint. As long as our program is able to accept Spotify credentials and use them to view playlist info, those credentials don't _have_ to be saved. Yet.

**Comment by deansgotbeans** [comment]
I can't be of help re: front end, but I can offer a snippet from a previous implementation of mine with spotipy

```
import spotipy
from spotipy.oauth2 import SpotifyOAuth
import webbrowser

CLIENT_ID = 'insert client id here'                                                  
CLIENT_SECRET = 'and secret here'
REDIRECT_URI = 'http://localhost:8585/callback'
SCOPE = 'playlist-read-private'  # In case you want to retrieve self-made playlists too                           

sp = spotipy.Spotify(auth_manager=SpotifyOAuth(client_id=CLIENT_ID, client_secret=CLIENT_SECRET, redirect_uri=REDIRECT_URI, scope=SCOPE))
webbrowser.open(sp.auth_manager.get_authorize_url())
input("Input entire token in address bar after web browser completes loading.")

playlists= sp.current_user_playlists()
playlist_data = {playlist['name']: playlist['id'] for playlist in playlists['items']}
print(f"{len(playlist_data)} playlists: {playlist_data}")

```

 Using the playlist ID, you could then iterate through and retrieve data from each song using the various spotipy endpoints
